## https://chat.openai.com/share/112c9e59-7206-4be6-ac29-3418c4096ea6
## Tested with ubuntu focal 20.04: Works

---
- name: Update system and install docker
  hosts: webdock

- name: Include update and install playbook
  ansible.builtin.import_playbook: ../playbooks/update-and-install.yml