## Tested with ubuntu focal 20.04: Works

- name: Run apt-get update
  become: yes
  apt: update_cache=yes

- name: Run autoremove
  become: yes
  apt: autoremove=yes
  
- name: Run autoclean
  become: yes
  apt: autoclean=yes
  