- name: Git checkout
  hosts: localhost
  tasks:

  - name: Checkout git repo
    ansible.builtin.git:
      repo: 'https://github.com/jd-apprentice/ansible-playbooks.git'
      dest: ./repo

  - name: enter repo folder and delete everything except the ansible folder
    ansible.builtin.shell: |
      cd ./repo
      find . -mindepth 1 -maxdepth 1 ! -name 'ansible' -exec rm -rf {} +

  - name: move the ansible folder outside and delete the repo folder
    ansible.builtin.shell: |
      mv ./repo/ansible ./
      rm -rf ./repo